name: scrape-kattis-scores

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scrape.py

      - name: Commit & push if CSV changed
        run: |
          git config user.name  "kattis-bot"
          git config user.email "actions@users.noreply.github.com"
          if git diff --quiet --exit-code points.csv; then
            echo "No change – skip commit"
          else
            git add points.csv
            git commit -m "data: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
